### ISSUE TITLE
Arbitrary sample rate and contacts

### ISSUE THREAD

**Issue by gogolgrind** [EliosMolina/audio_degrader#1]
Hi!
Currently, I am interested in audio augmentation techniques for one of my machine learning projects. And your small library is a good baseline for such purposes.
Could you provide to me your contacts for further questions?
E.g. one of the questions is the following. How to apply the noise addiction to some audio with arbitrary sample rate?  It is just changing some constants of your code, am I right? If so, could you guide me for right direction?

Thanks.

**Comment by emilio-molina** [comment]
Hi gogolgrind,

Thanks for your interest. I wanted to update a bit this library, and your request is a good excuse for it. What do you need? Just to use arbitrary sample rates?

**Comment by gogolgrind** [comment]
Hello, just for now yes, ability to use arbitrary sample rates would be nice.
Also, could you share materials that you used during audio_degrader development?

Thanks.

**Comment by emilio-molina** [comment]
Hi, I made a commit to master branch with some changes to allow any sample rate. It is pending to include some test examples, since now the options of the script have changed a bit. Let me know if you are able to make it run.

What do you mean about the materials?

**Comment by gogolgrind** [comment]
By materials I mean, books, blog-posts etc. that can be helpful for signal\audio processing studies. could you recommend me anything?

Again, thanks for the update.

**Comment by gogolgrind** [comment]
Also, Can I use partially your code if i decide develop my own library? How can I refer to you in this case?
Now I am interested in  realtime batch-mode augmentation to train deep networks. And as I said you code is a very good baseline

**Comment by emilio-molina** [comment]
I don't have any specific materials about this, sorry!
Of course, please use it wherever you want.
